//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "comments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub motif_id: i32,
    pub parent_id: Option<i32>,
    pub offset: Option<i32>,
    pub content: String,
    pub author_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::profiles::Entity",
        from = "Column::AuthorId",
        to = "super::profiles::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Profiles,
    #[sea_orm(
        belongs_to = "super::motifs::Entity",
        from = "Column::MotifId",
        to = "super::motifs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Motifs,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::comment_likes::Entity")]
    CommentLikes,
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profiles.def()
    }
}

impl Related<super::motifs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Motifs.def()
    }
}

impl Related<super::comment_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentLikes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
