//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "isrc_metadata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub isrc: String,
    pub name: String,
    pub artist: String,
    pub cover_art_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::isrc_metadata_status::Entity")]
    IsrcMetadataStatus,
}

impl Related<super::isrc_metadata_status::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IsrcMetadataStatus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
