/*
 * Copyright 2022 Julian Ostarek
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub mod prelude;

pub mod collection_motifs;
pub mod collections;
pub mod comment_likes;
pub mod comments;
pub mod motif_likes;
pub mod motif_listeners;
pub mod motif_service_ids;
pub mod motifs;
pub mod profile_follows;
pub mod profiles;
pub mod refresh_tokens;
pub mod sea_orm_active_enums;
pub mod service_credentials;
pub mod users;

pub mod profiles_links;
