/*
 * Copyright 2022 Julian Ostarek
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::collection_motifs::Entity as CollectionMotifs;
pub use super::collections::Entity as Collections;
pub use super::comment_likes::Entity as CommentLikes;
pub use super::comments::Entity as Comments;
pub use super::motif_likes::Entity as MotifLikes;
pub use super::motif_listeners::Entity as MotifListeners;
pub use super::motif_service_ids::Entity as MotifServiceIds;
pub use super::motifs::Entity as Motifs;
pub use super::profile_follows::Entity as ProfileFollows;
pub use super::profiles::Entity as Profiles;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::service_credentials::Entity as ServiceCredentials;
pub use super::users::Entity as Users;
