//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "profile_follows")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub follower_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub followed_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::profiles::Entity",
        from = "Column::FollowedId",
        to = "super::profiles::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Profiles2,
    #[sea_orm(
        belongs_to = "super::profiles::Entity",
        from = "Column::FollowerId",
        to = "super::profiles::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Profiles1,
}

impl ActiveModelBehavior for ActiveModel {}
