DROP TABLE service_credentials;
DROP TABLE refresh_tokens;
DROP TABLE motif_service_ids;
DROP TABLE motif_listeners;
DROP TABLE motifs;
DROP TYPE service;
DROP TABLE profile_follows;
DROP TABLE profiles;
DROP TABLE users;